add additional arguments to `publish-sdk`
Adds the ability to skip publishing a multi-arch manifest
(`--skip-manifest`) or publish a multi-arch manifest with remote images
that were pushed beforehand (`--only-manifest`).

Signed-off-by: Patrick J.P. Culp <jpculp@amazon.com>

diff --git a/publish-sdk b/publish-sdk
--- a/publish-sdk
+++ b/publish-sdk
@@ -9,10 +9,13 @@ for opt in "$@"; do
       --version=*) VERSION="${optarg}" ;;
       --registry=*) REGISTRY="${optarg}" ;;
       --sdk-name=*) SDK_NAME="${optarg}" ;;
+      --short-sha=*) SHORT_SHA="${optarg,,}" ;;
+      --skip-manifest=*) SKIP_MANIFEST="${optarg,,}" ;;
+      --only-manifest=*) ONLY_MANIFEST="${optarg,,}" ;;
    esac
 done
 
-for required_arg in VERSION REGISTRY SDK_NAME; do
+for required_arg in VERSION REGISTRY SDK_NAME SHORT_SHA; do
   [ -z "${!required_arg}" ] && echo "${required_arg} not set!" >&2 && exit 1
 done
 
@@ -46,65 +49,72 @@ update_image() {
     arm64) alt_docker_arch="amd64" ;;
   esac
 
-  if ! docker image inspect "${local_image}-${host_arch}" >/dev/null 2>&1 ; then
-    echo "did not find ${local_image}-${host_arch}, skipping it ..." >&2
-    return
+  local local_host_arch_image="${local_image}-${SHORT_SHA}-${host_arch}"
+  local remote_host_arch_image="${remote_image}-${SHORT_SHA}-${host_arch}"
+  local remote_alt_arch_image="${remote_image}-${SHORT_SHA}-${alt_arch}"
+
+  if [[ "${ONLY_MANIFEST:-"false"}" != "true" ]]; then
+    if ! docker image inspect "${local_host_arch_image}" >/dev/null 2>&1 ; then
+      echo "did not find ${local_host_arch_image}, skipping it ..." >&2
+      return
+    fi
+
+    if ! docker tag "${local_host_arch_image}" "${remote_host_arch_image}" ; then
+      echo "failed to tag ${remote_host_arch_image}" >&2 && exit 1
+    fi
+
+    # push the image, if it exists locally
+    if ! docker push "${remote_host_arch_image}" ; then
+      echo "failed to push ${remote_host_arch_image}" >&2 && exit 1
+    fi
   fi
 
-  if ! docker tag "${local_image}-${host_arch}" "${remote_image}-${host_arch}" ; then
-    echo "failed to tag ${remote_image}-${host_arch}" >&2 && exit 1
-  fi
+  if [[ "${SKIP_MANIFEST:-"false"}" != "true" ]]; then
+    # clean up any cached local copy of the manifest
+    manifest_dir="${HOME}/.docker/manifests"
+    mkdir -p "${manifest_dir}"
+    find "${manifest_dir}" -type f -delete
+    find "${manifest_dir}" -mindepth 1 -type d -delete
 
-  # push the image, if it exists locally
-  if ! docker push "${remote_image}-${host_arch}" ; then
-    echo "failed to push ${remote_image}-${host_arch}" >&2 && exit 1
-  fi
+    if ! docker manifest inspect "${remote_alt_arch_image}" >/dev/null 2>&1 ; then
+      echo "could not find ${remote_alt_arch_image}, skipping manifest creation" >&2
+      return
+    fi
 
-  # clean up any cached local copy of the manifest
-  manifest_dir="${HOME}/.docker/manifests"
-  mkdir -p "${manifest_dir}"
-  find "${manifest_dir}" -type f -delete
-  find "${manifest_dir}" -mindepth 1 -type d -delete
+    local image="${remote_image##*/}"
+    local repo="${image%:*}"
 
-  if ! docker manifest inspect "${remote_image}-${alt_arch}" >/dev/null 2>&1 ; then
-    echo "could not find ${remote_image}-${alt_arch}, skipping manifest creation" >&2
-    return
-  fi
+    # clean up any remote (ECR) copy of the manifest
+    if [[ "${REGISTRY}" =~ ^public\.ecr\.aws\/ ]]; then
+      aws ecr-public batch-delete-image \
+        --repository-name "${repo}" \
+        --image-ids imageTag="${VERSION}" \
+        --region "us-east-1"
+    elif [[ "${REGISTRY}" =~ ^[0-9]+\.dkr\.ecr\.[a-z0-9-]+\.amazonaws\.com$ ]]; then
+      aws ecr batch-delete-image \
+        --repository-name "${repo}" \
+        --image-ids imageTag="${VERSION}"
+    fi
 
-  local image="${remote_image##*/}"
-  local repo="${image%:*}"
+    if ! docker manifest create "${remote_image}" \
+        "${remote_host_arch_image}" "${remote_alt_arch_image}" ; then
+      echo "failed to create manifest ${remote_image}" >&2 && exit 1
+    fi
 
-  # clean up any remote (ECR) copy of the manifest
-  if [[ "${REGISTRY}" =~ ^public\.ecr\.aws\/ ]]; then
-    aws ecr-public batch-delete-image \
-      --repository-name "${repo}" \
-      --image-ids imageTag="${VERSION}" \
-      --region "us-east-1"
-  elif [[ "${REGISTRY}" =~ ^[0-9]+\.dkr\.ecr\.[a-z0-9-]+\.amazonaws\.com$ ]]; then
-    aws ecr batch-delete-image \
-      --repository-name "${repo}" \
-      --image-ids imageTag="${VERSION}"
-  fi
+    if ! docker manifest annotate "${remote_image}" \
+        "${remote_host_arch_image}" --arch "${docker_arch}" ; then
+      echo "failed to annotate manifest ${remote_image} with ${remote_host_arch_image}" >&2 && exit 1
+    fi
 
-  if ! docker manifest create "${remote_image}" \
-      "${remote_image}-${host_arch}" \
-      "${remote_image}-${alt_arch}" ; then
-    echo "failed to create manifest ${remote_image}" >&2 && exit 1
-  fi
+    if ! docker manifest annotate "${remote_image}" \
+        "${remote_alt_arch_image}" --arch "${alt_docker_arch}" ; then
+      echo "failed to annotate manifest ${remote_image} with ${remote_alt_arch_image}" >&2 && exit 1
+    fi
 
-  if ! docker manifest annotate "${remote_image}" \
-      "${remote_image}-${host_arch}" --arch "${docker_arch}" ; then
-    echo "failed to annotate manifest ${remote_image} with ${remote_image}-${host_arch}" >&2 && exit 1
-  fi
-
-  if ! docker manifest annotate "${remote_image}" \
-      "${remote_image}-${alt_arch}" --arch "${alt_docker_arch}" ; then
-    echo "failed to annotate manifest ${remote_image} with ${remote_image}-${alt_arch}" >&2 && exit 1
-  fi
-
-  # push the manifest and remove the local cache
-  if ! docker manifest push --purge "${remote_image}" ; then
-    echo "failed to push ${remote_image}" >&2 && exit 1
+    # push the manifest and remove the local cache
+    if ! docker manifest push --purge "${remote_image}" ; then
+      echo "failed to push ${remote_image}" >&2 && exit 1
+    fi
   fi
 }
 
